In [4]:
import pandas as pd
import numpy as np

abundance_df = pd.read_csv('output/Final_Abundance_2008_2023.csv')
percent_df = pd.read_csv('output/Final_Percent_2009_2023.csv')

In [5]:
abundance_df

,Unnamed: 0,Sample_Point_(SP),Year,Latitude,Longitude,Depth,Rake_Abundance,Rake_Abundance_#,Alisma_gramineum,Benthic_Filamentous_Algae,...,Potamogeton_zosteriformis,Ranunculus_trichophyllus,Riccia_fluitans,Spirodela_polyrhiza,Stuckenia_pectinata,Stuckenia_vaginata,Utricularia_vulgaris,Vallisneria_americana,Wolffia_columbiana,Zannichellia_palustris
0,0,1,2008,42.977652,-75.887120,0.3048,NaN,NaN,NaN,S,...,NaN,T,NaN,M,NaN,NaN,M,NaN,M,NaN
1,1,2,2008,42.977520,-75.887213,0.3048,NaN,NaN,NaN,T,...,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,S,NaN
2,2,3,2008,42.977661,-75.887699,0.6096,NaN,NaN,NaN,NaN,...,NaN,S,NaN,NaN,NaN,NaN,T,NaN,T,NaN
3,3,4,2008,42.977674,-75.888337,0.6096,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,5,2008,42.977542,-75.889355,0.6096,NaN,NaN,NaN,NaN,...,NaN,S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4857,297,300,2023,NaN,NaN,NaN,M,NaN,NaN,NaN,...,T,NaN,NaN,NaN,T,NaN,NaN,T,NaN,NaN
4858,298,301,2023,NaN,NaN,NaN,M,NaN,NaN,NaN,...,T,NaN,NaN,NaN,T,NaN,T,T,NaN,NaN
4859,299,302,2023,NaN,NaN,NaN,T,NaN,NaN,NaN,...,T,NaN,NaN,NaN,NaN,NaN,NaN,T,NaN,NaN
4860,300,303,2023,NaN,NaN,NaN,S,NaN,NaN,NaN,...,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4861,301,304,2023,NaN,NaN,NaN,S,NaN,NaN,NaN,...,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
percent_df

,Unnamed: 0,Sample_Point_(SP),Year,Date,Rake_toss_#,Latitude,Longitude,Depth,Rake_Abundance,PERCENT,...,Riccia_fluitans,Spirodela_polyrhiza,Stuckenia_pectinata,Stuckenia_vaginata,Utricularia_vulgaris,Vallisneria_americana,Wolffia_columbiana,Zannichellia_palustris,Zosterella_dubia,Abundance_calcs
0,0,1,2009,NaN,1.0,42.977680,75.886960,0.3,D,100.05,...,NaN,0.01,NaN,NaN,NaN,NaN,0.01,NaN,NaN,NaN
1,1,1,2009,NaN,2.0,42.977680,75.886960,NaN,D,100.01,...,NaN,0.01,NaN,NaN,6.0,NaN,1.00,NaN,1.0,NaN
2,2,2,2009,NaN,1.0,42.977520,75.887213,0.5,D,100.08,...,NaN,0.01,1.0,NaN,NaN,1.0,0.01,NaN,NaN,NaN
3,3,2,2009,NaN,2.0,42.977520,75.887213,NaN,D,100.04,...,NaN,0.01,NaN,NaN,2.0,2.0,0.01,NaN,1.0,NaN
4,4,3,2009,NaN,1.0,42.977661,75.887699,1.0,M,100.03,...,NaN,0.01,NaN,NaN,NaN,NaN,0.01,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9113,599,302,2023,2023-08-31,2.0,42.961837,-75.872214,2.1,T,NaN,...,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN
9114,600,303,2023,2023-08-08,1.0,42.948490,-75.866480,2.6,S,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9115,601,303,2023,2023-08-08,2.0,42.948490,-75.866480,2.6,S,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9116,602,304,2023,2023-08-08,1.0,42.948360,-75.866510,2.8,O,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9117,603,304,2023,2023-08-08,2.0,42.948360,-75.866510,2.8,S,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
percent_cols = list(percent_df.columns)
abundance_cols = list(abundance_df.columns)

for col in percent_cols:
    if col not in abundance_cols:
        print(col)

Date
Rake_toss_#
PERCENT
Juncus_sp.
Ludwigia_sp.
Zosterella_dubia
Abundance_calcs

In [8]:
for col in abundance_cols:
    if col not in percent_cols:
        print(col)

# percent df is also missing 2008 data, there is only abundance data for that year.

Rake_Abundance_#
Potamogeton_pectinatus

In [10]:
common_cols = list(set(abundance_cols) & set(percent_cols))
common_cols

['Lemna_minor',
 'Floating_Filamentous_Algae',
 'Spirodela_polyrhiza',
 'Unnamed: 0',
 'Myriophyllum_sibiricum',
 'Stuckenia_pectinata',
 'Riccia_fluitans',
 'Najas_flexilis',
 'Potamogeton_amplifolius',
 'Nitella_flexilis',
 'Nitellopsis_obtusa',
 'Hypericum_ellipticum',
 'Potamogeton_crispus_turions',
 'Potamogeton_illinoensis',
 'Potamogeton_praelongus',
 'Wolffia_columbiana',
 'Myriophyllum_spicatum',
 'Potamogeton_richardsonii',
 'Zannichellia_palustris',
 'Ranunculus_trichophyllus',
 'Fontinalis_sp.',
 'Elodea_sp.',
 'Nuphar_variegata',
 'Chara_vulgaris',
 'Lemna_trisulca',
 'Utricularia_vulgaris',
 'Ceratophyllum_demersum',
 'Megalodonta_beckii',
 'Depth',
 'Potamogeton_crispus',
 'Latitude',
 'Potamogeton_gramineus',
 'Hydrocharis_morsus-ranae',
 'Najas_guadalupensis',
 'Longitude',
 'Callitriche_hermaphroditica',
 'Nymphaea_odorata',
 'Potamogeton_pusillus',
 'Alisma_gramineum',
 'Sample_Point_(SP)',
 'Year',
 'Potamogeton_foliosus',
 'Polygonum_amphibium',
 'Stuckenia_vaginata',
 'Potamogeton_zosteriformis',
 'Heteranthera_dubia',
 'Rake_Abundance',
 'Vallisneria_americana',
 'Benthic_Filamentous_Algae',
 'Pithophora_sp.']

In [ ]:
# merge these 2 dfs along (Sample_Point_(SP) || Latitude & Longitude) and (Rake_toss_#). add _p or _a to col name to indicate which df it came from

# follow ERD and TO-DO for DB-prep: 
    # https://www.notion.so/Rake-Toss-Data-ERD-notes-from-Data-Cleaning-4c87f698ab77437b9b58f73de03e2e73?pvs=4
# or in app CLA > Lake Database: Rake Toss ERD & notes from Data Cleaning

# read this first - may want to do one table at a time
# https://baronchibuike.medium.com/how-to-read-csv-file-and-save-the-content-to-the-database-in-django-rest-256c254ef722